### ISSUE TITLE
kernel name is garbled when using HCC_PROFILE=2

### ISSUE THREAD

**Issue by huangjw08** [RadeonOpenCompute/hcc#1151]
I using roc_blas library to do HPL Benchmark. And the program works fine. But when I using this command to generate log file:
 `HCC_PROFILE=2 ./executeName &> prof.out`
I found there are some garbled characters in this output log file.
![2019-05-13_161455](https://user-images.githubusercontent.com/13818576/57605971-77fd1980-759a-11e9-9741-ae04188c51c2.jpg)

And I think there are mainly three kernel functions:
**HPL_dlaswp: to perform Row exchanges of matrices**
**rocblas_dtrsm: to perform DTRSM calculations**
**rocblas_dgemm: to perform DGEMM calculations**
But I could not find any infos about HPL_dlaswp and rocblas_dtrsm in prof.out file. so I guess both two kernel names may be garbled in generating prof.out file.

My Environment is as follows:
```
Ubuntu 16.04TLS
ROCm-2.3
rocblas-2.2
gfx-906
```

**Comment by jeffdaily** [comment]
Which version of hcc are you using?  This should have been fixed by https://github.com/RadeonOpenCompute/hcc/pull/1111.   The fix did not make it in time for our roc-2.4.x branching, but will be part of roc-2.5.x.

**Comment by huangjw08** [comment]
@jeffdaily The version of hcc clang is 9.0.0
![2019-05-14_090533](https://user-images.githubusercontent.com/13818576/57663657-788fc180-7627-11e9-886e-3d2974fc553d.png)

**Comment by jeffdaily** [comment]
If you cannot wait for ROCm 2.5 to be released, the only alternative would be for you to build your own hcc and replace `libmcwamp_hsa.so` with a patched version based on the ROCm 2.3 branch of hcc. 
 I have done this in one of my fork's branches, so there is no need for you to cherry-pick the fix. 
 Something like the following:

```bash
git clone --recursive -b roc-2.3.x-prof https://github.com/jeffdaily/hcc.git
cd hcc
mkdir build
cd build
cmake ..
make -j $(nproc)
cp lib/libmcwamp_hsa.so /opt/rocm/hcc/lib/libmcwamp_hsa.so
```

If you upgrade to ROCm 2.4, the issue remains, and I have yet another branch in my hcc fork that has applied the patch.  Then `git clone --recursive -b roc-2.4.x-prof https://github.com/jeffdaily/hcc.git` instead.

Again, this should be fixed in the ROCm 2.5 release.

**Comment by huangjw08** [comment]
@jeffdaily I have built your patched version of hcc and copy libmcwam_hsa.so to /opt/rocm/hcc/lib/ directory. But it seems does not work.
 
![2019-05-15_100800](https://user-images.githubusercontent.com/13818576/57743900-8f9ee400-76f9-11e9-8f18-cfdddc5d6f7a.jpg)

Then I reactived my original libmcwam_hsa.so. This program works fine again.
Is there anything wrong?

**Comment by scchan** [comment]
If you upgrade to a different version of HCC then you'll probably have to rebuild HIP and everthing that depends on it.
If the rest of your stack is still on 2.3, then apply #1111 to the 2.3.x branch and build/copy libmcwamp_hsa.so into /opt/rocm/hcc/lib
