### ISSUE TITLE
Problem compiling OpenCV example.

### ISSUE THREAD

**Issue by briansp2020** [RadeonOpenCompute/hcc#47]
Hi,
I'm trying to compile OpenCV example using hcc and am having link error. It's a simple example that loads and saves an image. I compile it with the following command

`hcc `hcc-config --cxxflags` test.cpp -lstdc++ -lopencv_highgui -lopencv_imgcodecs -lopencv_core`

and get

`/tmp/tmp.dCfO0GVjM9/test-5fdd60.host.o: In function `main':
/tmp/test-d09a2a.s.bc:(.text+0x65b): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::__1::vector<int, std::__1::allocator<int> > const&)'`

Using g++, it compiles without any issue. Is this an hcc problem? I'm using OpenCV 3.1 compiled locally on my machine. It's interesting that only imwrite is not found. imread, which I believe is in the same library libopencv_imgcodecs, is found without a problem.

[test.txt](https://github.com/RadeonOpenCompute/hcc/files/244491/test.txt)

My ultimate goal is to convert Udacity Parallel Programming class assignment to run on ROCm. I'm using hip to convert [problem set 1 code](https://github.com/udacity/cs344/tree/master/Problem%20Sets/Problem%20Set%201) from CUDA to hcc and am having problem with linking OpenCV library.

[ps1.zip](https://github.com/RadeonOpenCompute/hcc/files/244501/ps1.zip)

**Comment by whchung** [comment]
@briansp2020 your build command may impose some problem:

```
hcc `hcc-config --cxxflags` test.cpp -lstdc++ -lopencv_highgui -lopencv_imgcodecs -lopencv_core
```

```hcc-config -cxxflags``` will tell hcc to use libc++, but you also specified to link with libstdc++ . So that's where problem may occur.

To my understanding HIP team are working on a solution to cope with HIP/CUDA applications which must link with libstdc++ , and they should have something working now. I'd suggest you contact them at: https://github.com/AMDComputeLibraries/hip  to see where they are.

**Comment by briansp2020** [comment]
I was able to compile OpenCV example using ROCm-1.1.1
