### ISSUE TITLE
libcxxabi

### ISSUE THREAD

**Issue by smithakihide** [RadeonOpenCompute/hcc#547]
hello.
when I install ROCm from the repository of http://repo.radeon.com/rocm/yum/rpm/ using below command as described in https://github.com/RadeonOpenCompute/ROCm,

sudo yum install rocm

then the below error occurred.
Error: Package: hcc-1.0.17412-1.x86_64 (remote)
           Requires: libcxxabi

although I searched what is libcxxabi, finally I could not get any idea for it.
please help me.

**Comment by tstellar** [comment]
What version of fedora are you on?  Did you try yum install libcxxabi ?

**Comment by smithakihide** [comment]
thank you.
CentOS 7.3. clean installed.
yes I tried. but the result is here.

Loaded plugins: fastestmirror, langpacks
base
epel/x86_64/metalink
extras
remote
updates
updates/7/x86_64/primary_db
Loading mirror speeds from cached hostfile
 * epel: ftp.riken.jp
No package libcxxabi available.
Error: Nothing to do

**Comment by aaronenyeshi** [comment]
It’s strange because it should have been added to the ROCm yum repo. Here are the steps to create it manually.

Installing C++ and C++ ABI packages to support HCC

The HCC compiler requires specific C++ headers and binaries to be able to run. These binaries are not available on the CentOS/RHEL repositories, so they must be installed using release builds following these instructions:

1. Install Subversion, Clang and llvm-devel
sudo yum install svn clang llvm-devel cmake3
2. Build libcxx without libcxxabi
svn co http://llvm.org/svn/llvm-project/libcxx/branches/release_50/ libcxx
cd libcxx
mkdir build; cd build
# Specifying CMAKE_BUILD_TYPE to Release shall generate performance optimized code.
cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
sudo make install
cd ..; rm tmp -rf; cd ..
3. Build libcxxabi with libc++
svn co http://llvm.org/svn/llvm-project/libcxxabi/branches/release_50/ libcxxabi
cd libcxxabi
mkdir build; cd build
cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLIBCXXABI_LIBCXX_INCLUDES=../../libcxx/include ..
sudo make install
cd ../..
4. Build libcxx with libcxxabi
cd libcxx
mkdir build; cd build
# This time, we want to compile libcxx with libcxxabi, so specify LIBCXX_CXX_ABI=libcxxabi and the path to libcxxabi headers LIBCXX_LIBCXXABI_INCLUDE_PATHS.
cmake3 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DLIBCXX_CXX_ABI=libcxxabi -DLIBCXX_CXX_ABI_INCLUDE_PATHS=../../libcxxabi/include ..
sudo make install
These two packages are required for compiling and running HCC supported programs, including HIP programs.

**Comment by smithakihide** [comment]
thank you for a lot of things.
I tried those command to build libc++abi and libc++, but I still couldn't install rocm with the same error message of "rocm Requires: libcxxabi".

I also tried to compile the c++ program using `clang++ test.cpp -std=c++11 -stdlib=libc++ -lc++abi 
`
to confirm all environments was correctly installed. this worked. 

here is the test code.

`#include <iostream>
int main()
{
std::cout << "a\n";
return 0;
}`

I am glad if some one help me.

**Comment by tstellar** [comment]
On centos, I would recommend using libstdc++ as your c++ library instead of libc++.  It looks like passing -DUSE_LIBCXX=OFF to cmake when you configure will disable libc++.

**Comment by smithakihide** [comment]
thank you.
dose it work to compile rocm also?

**Comment by tstellar** [comment]
I don't understand your question.

**Comment by smithakihide** [comment]
sorry,
what I wanted to say is,
is it possible to use the way you told me to install rocm?

**Comment by chipfreitag** [comment]
I'm having similar issues installing with RHEL 7.3.
The dependencies ROCm (1.6-180) are complaining about are:
libunwind-devel libcxx libcxxabi libstdc++-static

I was able to get libunwind using yum install libunwind.686.  But  the others's don't seem to be available.
You're really having us build libcxx?

**Comment by scchan** [comment]
On RHEL 7.3, we are going to support hcc with developer toolset version 7, which has gcc 7.2, and we are going to use the libstdc++ instead of libc++ as the C++ runtime.  There shouldn't be a need for libcxx anymore.
